### ISSUE TITLE
[RFC] Create an RFC process for development standard changes

### ISSUE THREAD

**Issue by resir014** [kata-ai/development-standard#3]
## Summary

Create a RFC process using the development tools we use (e.g. GitHub Issue templates). Anyone in Kata.ai team can propose changes to this development styleguide, and the Core team approves them.

## Motivation

The development standard needs to be a living document, and changes made to it needs to be agreed upon by all members. Therefore, an RFC process needs to be created to introduce a process to make changes to this styleguide.

## Exceptions

N/A

## Drawbacks

N/A

## Additional Context

The PR description here outlines the rough template that we can use for the RFC. We can change this throughout the lifetime of this PR when necessary.

We can implement this using GitHub's Issue templates (`.github/ISSUE_TEMPLATE/rfc.md`). I don't know if Gitlab has a similar system.

**Comment by mamaz** [comment]
Nice one, let's use this.

**Comment by resir014** [comment]
Implemented: https://gitlab.com/kata-ai/rfcs/rfc
